name: Run Tests On PR

on:
  pull_request:
    branches:
      - master

jobs:
  pr-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          yarn

      - name: Run Tests
        run: |
          JWT_PRIVATE_KEY=ABC
          yarn test:cov
